app.repository.type=database

# Production Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-proud-sea-aml792rn-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oPyp1QvwFnA6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
db.pool.maxSize=10
db.pool.minIdle=2
db.pool.connectionTimeoutMs=30000
db.pool.idleTimeoutMs=600000
db.pool.maxLifetimeMs=1800000

# Test Database (H2)
test.db.url=jdbc:h2:mem:quantity_measurement_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
test.db.username=sa
test.db.password=
test.db.driverClassName=org.h2.Driver

logging.level=INFO